### ISSUE TITLE
Remove unneeded gradle plugin dependency.

### ISSUE THREAD

**Issue by jackflip** [TheAltening/API-Java#1]
Hi,
In your build.gradle file I see you are using the shadow-jar. However, you aren't using any dependencies that would enforce the usage of that jar. Therefore, the use to only minimize the dependency size is ridiculous. With that regard, removing the dependency will most likely make it more minimal than just running that function with the gradle plugin.

**Comment by Trol** [comment]
2880d151a2f7a3f7a1dae370539ec879645a366c Fixed.
